//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrorMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Resources.ValidationErrorMessagesResource", typeof(ValidationErrorMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}باید برابر {1} باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_EQUAL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت {0} نا معتبر است..
        /// </summary>
        internal static string VALIDATION_ERROR_FORMAT_INCORRECT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_FORMAT_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}باید بیشتر از {1} باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_GREATER_THAN {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تکراری است..
        /// </summary>
        internal static string VALIDATION_ERROR_IS_DUPLICATED {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_IS_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} اجباری است..
        /// </summary>
        internal static string VALIDATION_ERROR_IS_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}باید کمتر از {1} باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_LESS_THAN {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} باید کوچکتر {1} باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_MAX_VALUE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید حداقل {1} کاراکتر باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_MIN_STRING_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MIN_STRING_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} باید بزرگتر {1} باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_MIN_VALUE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید {1} باشد..
        /// </summary>
        internal static string VALIDATION_ERROR_MUST_BE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MUST_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید یکتا باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_MUST_BE_UNIQUE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MUST_BE_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید {1} داشته باشد..
        /// </summary>
        internal static string VALIDATION_ERROR_MUST_HAVE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MUST_HAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نباید {1} داشته باشد..
        /// </summary>
        internal static string VALIDATION_ERROR_MUST_HAVE_NOT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MUST_HAVE_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نباید {1} باشد..
        /// </summary>
        internal static string VALIDATION_ERROR_MUST_NOT_BE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MUST_NOT_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} باید مقدار داشته باشد.&quot;.
        /// </summary>
        internal static string VALIDATION_ERROR_NOT_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} برابر  {1} نیست .
        /// </summary>
        internal static string VALIDATION_ERROR_NOT_EQUAL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NOT_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} وجود ندارد..
        /// </summary>
        internal static string VALIDATION_ERROR_NOT_EXIST {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} یافت نشد..
        /// </summary>
        internal static string VALIDATION_ERROR_NOT_FOUND {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نباید نال باشد..
        /// </summary>
        internal static string VALIDATION_ERROR_NOT_NULL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} نامعتبر است..
        /// </summary>
        internal static string VALIDATION_ERROR_NOT_VALID {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بین {2} و {1} کاراکتر باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_STRING_LENGTH_BETWEEN {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_STRING_LENGTH_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید حداکثر {1} کاراکتر باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_STRING_MAX_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_STRING_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بین {2} و {1} باشد.
        /// </summary>
        internal static string VALIDATION_ERROR_VALUE_BETWEEN {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_VALUE_BETWEEN", resourceCulture);
            }
        }
    }
}
